name: dio_cache_interceptor
description: Dio HTTP cache interceptor with multiple stores respecting HTTP directives (or not).
repository: https://github.com/llfbandit/dio_cache_interceptor
issue_tracker: https://github.com/llfbandit/dio_cache_interceptor/issues

version: 3.4.4

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  # https://pub.dev/packages/dio
  dio: ">=5.2.0+1 <6.0.0"  
  # https://pub.dev/packages/uuid
  uuid: ">=3.0.7 <5.0.0"
  # https://pub.dev/packages/string_scanner
  string_scanner: ^1.1.0

dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^2.0.1
  # https://pub.dev/packages/test
  test: ^1.23.1
